name: My first workflow

on: push
jobs:
    first_job: 
        runs-on: self-hosted
        steps: 
          - name: welcome message
            run: echo "hi all" 
          - name: welcome message
            run: ls
          - name: welcome message
            run: cat Dockerfile
